### PR TITLE
add app name as lable to the widget layout

### PR DESCRIPTION
**Pull request by Saeed-Pooyanfar**
Just added app name as lable to the widget layout

Saeed Pooyanfar

### CODE REVIEW

**Comment by androidseb** [comment]
Thank you for the suggestion :-)
The code you proposed did not compile properly and the text was overlaying the icon, so I fixed it by adding the text below.
I also changed the imageview to be a button, that way the click feedback is visible.
Here is the commit link:
[https://github.com/androidseb/camerarestarter/commit/3b2abd57c319e89ffb486e717c4cb6d2f5da4313](https://github.com/androidseb/camerarestarter/commit/3b2abd57c319e89ffb486e717c4cb6d2f5da4313)

**Comment by Saeed-Pooyanfar** [comment]
Thanks for update ...
But widget became small now!
I just forgot to add RelativeLayout properties!
My code should works fine !

**Comment by androidseb** [comment]
I tested it the widget size was fine... Maybe I missed something, can you send me a screenshot of the rendering you have please?

**Comment by Saeed-Pooyanfar** [comment]
Yes, here you are ...
I think it's small compare with pervious version ...

**Pull request closed without merging**
